// @ts-nocheck
/**
 * Mock Payment Provider API
 * API for mocking payment provider integrations with webhooks, 3DS, and admin dashboard.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsTransaction } from '../models/ModelsTransaction';
import { HttpFile } from '../http/http';

export class ModelsThreeDSAuthenticateResponse {
    'success'?: boolean;
    'transaction'?: ModelsTransaction;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "ModelsTransaction",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsThreeDSAuthenticateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
