// @ts-nocheck
/**
 * Mock Payment Provider API
 * API for mocking payment provider integrations with webhooks, 3DS, and admin dashboard.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsWebhook {
    'active'?: boolean;
    'created_at'?: string;
    /**
    * JSON array of event types
    */
    'event_types'?: string;
    'id'?: number;
    'merchant_id'?: number;
    'retry_attempts'?: number;
    'secret'?: string;
    'timeout_seconds'?: number;
    'updated_at'?: string;
    'url'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "event_types",
            "baseName": "event_types",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "merchant_id",
            "baseName": "merchant_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "retry_attempts",
            "baseName": "retry_attempts",
            "type": "number",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeout_seconds",
            "baseName": "timeout_seconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsWebhook.attributeTypeMap;
    }

    public constructor() {
    }
}
