// @ts-nocheck
/**
 * Mock Payment Provider API
 * API for mocking payment provider integrations with webhooks, 3DS, and admin dashboard.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsTransaction {
    'amount'?: number;
    'amount_captured'?: number;
    'amount_refunded'?: number;
    'authorization_code'?: string;
    'card_id'?: number;
    'card_number_last4'?: string;
    'card_type'?: string;
    'created_at'?: string;
    'currency'?: string;
    'error_code'?: string;
    'error_message'?: string;
    'expires_at'?: string;
    'id'?: number;
    'merchant_id'?: number;
    'metadata'?: string;
    'parent_transaction_id'?: number;
    'payment_method'?: string;
    'status'?: string;
    'three_ds_authenticated'?: boolean;
    'three_ds_required'?: boolean;
    'three_ds_transaction_id'?: string;
    /**
    * charge, hold, capture, refund
    */
    'transaction_type'?: string;
    'updated_at'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "amount_captured",
            "baseName": "amount_captured",
            "type": "number",
            "format": ""
        },
        {
            "name": "amount_refunded",
            "baseName": "amount_refunded",
            "type": "number",
            "format": ""
        },
        {
            "name": "authorization_code",
            "baseName": "authorization_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "card_id",
            "baseName": "card_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "card_number_last4",
            "baseName": "card_number_last4",
            "type": "string",
            "format": ""
        },
        {
            "name": "card_type",
            "baseName": "card_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_code",
            "baseName": "error_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_message",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "expires_at",
            "baseName": "expires_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "merchant_id",
            "baseName": "merchant_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "string",
            "format": ""
        },
        {
            "name": "parent_transaction_id",
            "baseName": "parent_transaction_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "payment_method",
            "baseName": "payment_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "three_ds_authenticated",
            "baseName": "three_ds_authenticated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "three_ds_required",
            "baseName": "three_ds_required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "three_ds_transaction_id",
            "baseName": "three_ds_transaction_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "transaction_type",
            "baseName": "transaction_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}
