// @ts-nocheck
/**
 * Mock Payment Provider API
 * API for mocking payment provider integrations with webhooks, 3DS, and admin dashboard.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsDashboardResponse {
    'active_cards'?: number;
    'active_merchants'?: number;
    'active_scenarios'?: number;
    'failed_transactions'?: number;
    'successful_transactions'?: number;
    'total_amount'?: number;
    'total_transactions'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active_cards",
            "baseName": "active_cards",
            "type": "number",
            "format": ""
        },
        {
            "name": "active_merchants",
            "baseName": "active_merchants",
            "type": "number",
            "format": ""
        },
        {
            "name": "active_scenarios",
            "baseName": "active_scenarios",
            "type": "number",
            "format": ""
        },
        {
            "name": "failed_transactions",
            "baseName": "failed_transactions",
            "type": "number",
            "format": ""
        },
        {
            "name": "successful_transactions",
            "baseName": "successful_transactions",
            "type": "number",
            "format": ""
        },
        {
            "name": "total_amount",
            "baseName": "total_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "total_transactions",
            "baseName": "total_transactions",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsDashboardResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
