// @ts-nocheck
/**
 * Mock Payment Provider API
 * API for mocking payment provider integrations with webhooks, 3DS, and admin dashboard.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsCard {
    'card_number'?: string;
    /**
    * visa, mastercard, amex
    */
    'card_type'?: string;
    'cardholder_name'?: string;
    'created_at'?: string;
    'cvv'?: string;
    'description'?: string;
    'expiry_month'?: number;
    'expiry_year'?: number;
    'id'?: number;
    'require_3ds'?: boolean;
    /**
    * success, decline, insufficient_funds, etc.
    */
    'response_scenario'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "card_number",
            "baseName": "card_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "card_type",
            "baseName": "card_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardholder_name",
            "baseName": "cardholder_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "cvv",
            "baseName": "cvv",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiry_month",
            "baseName": "expiry_month",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiry_year",
            "baseName": "expiry_year",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "require_3ds",
            "baseName": "require_3ds",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "response_scenario",
            "baseName": "response_scenario",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsCard.attributeTypeMap;
    }

    public constructor() {
    }
}
