// @ts-nocheck
/**
 * Mock Payment Provider API
 * API for mocking payment provider integrations with webhooks, 3DS, and admin dashboard.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ServicesChargeRequest {
    'amount'?: number;
    'api_key'?: string;
    'card_number'?: string;
    'card_type'?: string;
    'cardholder_name'?: string;
    'currency'?: string;
    'cvv'?: string;
    'expiry_month'?: number;
    'expiry_year'?: number;
    'three_ds_authenticated'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "api_key",
            "baseName": "api_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "card_number",
            "baseName": "card_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "card_type",
            "baseName": "card_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardholder_name",
            "baseName": "cardholder_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "cvv",
            "baseName": "cvv",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiry_month",
            "baseName": "expiry_month",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiry_year",
            "baseName": "expiry_year",
            "type": "number",
            "format": ""
        },
        {
            "name": "three_ds_authenticated",
            "baseName": "three_ds_authenticated",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServicesChargeRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
